AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test-function
      Runtime: python3.11
      CodeUri: function/
      Handler: app.handler
      MemorySize: 128
      Timeout: 30
